// Base64-encode the engine's wasm into src/generated/wasm-inline.ts, so the default
// IIFE build can inline it (one-tag drop, no second fetch). Run before the build.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

const wasmPath = resolve(root, "node_modules/@dignetwork/dig-urn-resolver/web/dig_urn_resolver_bg.wasm");
const wasm = readFileSync(wasmPath);
const base64 = wasm.toString("base64");

const outDir = resolve(root, "src/generated");
mkdirSync(outDir, { recursive: true });
const banner = "// AUTO-GENERATED by scripts/gen-wasm.mjs — DO NOT EDIT.\n";
writeFileSync(resolve(outDir, "wasm-inline.ts"), `${banner}export const WASM_BASE64 = "${base64}";\n`);

console.log(`gen-wasm: inlined ${wasm.byteLength} bytes → ${(base64.length / 1024).toFixed(1)} KiB base64`);
